name: Publish to NPM
on:
  push:
    branches:
      - 'main'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - run: yarn test --ci --coverage --maxWorkers=2
      - run: npm config set registry https://registry.npmjs.org && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
